[package]
name = "gradestalib"
version = "0.1.0"
authors = ["Timothy Hobbs"]
build = "build.rs"

[dependencies]
quick-protobuf = "0.6.2"
zmq = "0.8"
maplit = "1.0.1"
bytes = "0.4.10"
prost = "0.4.0"
prost-derive = "0.4.0"
notify = "4.0.6"

[build-dependencies]
prost-build = "0.4.0"
