[package]
name = "gradestalib"
version = "0.1.0"
authors = ["Timothy Hobbs"]
build = "build.rs"

[dependencies]
quick-protobuf = "0.6.2"
zmq = "0.8"
maplit = "1.0.1"

[build-dependencies]
pb-rs = "0.7.0"
